/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoUseBubble: typeof import('./src/components/demo-useBubble.vue')['default']
    DemoUseBubbleList: typeof import('./src/components/demo-useBubbleList.vue')['default']
    DemoUseConversations: typeof import('./src/components/demo-useConversations.vue')['default']
    DemoUseSender: typeof import('./src/components/demo-useSender.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HooksUseXStreamScenarioSIP: typeof import('./src/components/hooks-useXStream-scenarioSIP.vue')['default']
    HooksUseXStreamScenarioSSE: typeof import('./src/components/hooks-useXStream-scenarioSSE.vue')['default']
    UseRecord: typeof import('./src/components/useRecord.vue')['default']
    UseSend: typeof import('./src/components/useSend.vue')['default']
  }
}
