/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A3ChatDemo: typeof import('./src/components/A3ChatDemo.vue')['default']
    AttachmentsDemo: typeof import('./src/components/AttachmentsDemo.vue')['default']
    BubbleDemo: typeof import('./src/components/BubbleDemo.vue')['default']
    BubbleListDemo: typeof import('./src/components/BubbleListDemo.vue')['default']
    ConversationsDemo: typeof import('./src/components/ConversationsDemo.vue')['default']
    copy: typeof import('./src/components/index copy.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FilesCardDemo: typeof import('./src/components/FilesCardDemo.vue')['default']
    MentionSenderDemo: typeof import('./src/components/MentionSenderDemo.vue')['default']
    PromptsDemo: typeof import('./src/components/PromptsDemo.vue')['default']
    SenderDemo: typeof import('./src/components/SenderDemo.vue')['default']
    TestEditorInputDemo: typeof import('./src/components/Test-EditorInputDemo.vue')['default']
    TestEditorSenderDemo: typeof import('./src/components/Test-EditorSenderDemo.vue')['default']
    ThinkingDemo: typeof import('./src/components/ThinkingDemo.vue')['default']
    ThoughtChainDemo: typeof import('./src/components/ThoughtChainDemo.vue')['default']
    UseRecordDemo: typeof import('./src/components/useRecordDemo.vue')['default']
    UseSendDemo: typeof import('./src/components/useSendDemo.vue')['default']
    UseXStreamSIPDemo: typeof import('./src/components/useXStreamSIPDemo.vue')['default']
    UseXStreamSSEDemo: typeof import('./src/components/useXStreamSSEDemo.vue')['default']
    WelcomeDemo: typeof import('./src/components/WelcomeDemo.vue')['default']
  }
}
