/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoUseBubble: typeof import('./src/components/demo-useBubble.vue')['default']
    DemoUseBubbleList: typeof import('./src/components/demo-useBubbleList.vue')['default']
    DemoUseSender: typeof import('./src/components/demo-useSender.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  }
}
