/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bubble: typeof import('./src/components/Bubble/index.vue')['default']
    BubbleList: typeof import('./src/components/BubbleList/index.vue')['default']
    ClearButton: typeof import('./src/components/Sender/components/ClearButton/index.vue')['default']
    Conversations: typeof import('./src/components/Conversations/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Item: typeof import('./src/components/Conversations/components/item.vue')['default']
    Loading: typeof import('./src/components/Sender/components/LoadingButton/loading.vue')['default']
    LoadingButton: typeof import('./src/components/Sender/components/LoadingButton/index.vue')['default']
    SendButton: typeof import('./src/components/Sender/components/SendButton/index.vue')['default']
    Sender: typeof import('./src/components/Sender/index.vue')['default']
    SpeechButton: typeof import('./src/components/Sender/components/SpeechButton/index.vue')['default']
    SpeechLoadingButton: typeof import('./src/components/Sender/components/SpeechLoadingButton/index.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/index.vue')['default']
  }
}
