/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Attachments: typeof import('./src/components/Attachments/index.vue')['default']
    Bubble: typeof import('./src/components/Bubble/index.vue')['default']
    BubbleList: typeof import('./src/components/BubbleList/index.vue')['default']
    ClearButton: typeof import('./src/components/EditorSender/components/ClearButton/index.vue')['default']
    Conversations: typeof import('./src/components/Conversations/index.vue')['default']
    EditorInput: typeof import('./src/components/EditorInput/index.vue')['default']
    EditorSender: typeof import('./src/components/EditorSender/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMention: typeof import('element-plus/es')['ElMention']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Indexbase: typeof import('./src/components/EditorSender/indexbase.vue')['default']
    Item: typeof import('./src/components/Conversations/components/item.vue')['default']
    Loading: typeof import('./src/components/BubbleList/loading.vue')['default']
    LoadingButton: typeof import('./src/components/EditorSender/components/LoadingButton/index.vue')['default']
    MentionSender: typeof import('./src/components/MentionSender/index.vue')['default']
    Prompts: typeof import('./src/components/Prompts/index.vue')['default']
    SendButton: typeof import('./src/components/EditorSender/components/SendButton/index.vue')['default']
    Sender: typeof import('./src/components/Sender/index.vue')['default']
    SpeechButton: typeof import('./src/components/EditorSender/components/SpeechButton/index.vue')['default']
    SpeechLoadingButton: typeof import('./src/components/EditorSender/components/SpeechLoadingButton/index.vue')['default']
    Thinking: typeof import('./src/components/Thinking/index.vue')['default']
    ThoughtChain: typeof import('./src/components/ThoughtChain/index.vue')['default']
    Typewriter: typeof import('./src/components/Typewriter/index.vue')['default']
    Welcome: typeof import('./src/components/Welcome/index.vue')['default']
  }
}
